keys:
  - &primary age1sseqwwa7fc0ftry8njyuagdg28fkmtdwmj6m7p3etjsj83suee3shfzjyz
creation_rules:
  - path_regex: secrets/spacestation.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: secrets/spacestation.lesser.json$
    key_groups:
      - age:
        - *primary
